### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kpsmail** [BuffMcBigHuge/text-generation-webui-edge-tts#11]
![屏幕截图 2024-04-07 224651](https://github.com/BuffMcBigHuge/text-generation-webui-edge-tts/assets/156741049/09ec1785-2985-4d1a-8cf8-5056509382bb)

Ask for answers

**Comment by Mero7979** [comment]
I have a similar problem.
I have tried all the solutions proposed in the Issue posts without success.
I tried clean install. But nothing. Click on the image to see better, Please.

![install_issue](https://github.com/BuffMcBigHuge/text-generation-webui-edge-tts/assets/160163445/596c0a6f-b28a-43d5-bd86-9705d4c1dcd7)

I will be grateful for your support.
Thank you so much.

**Comment by SencneS** [comment]
I too am getting this install error. I think it's missing a model but because it installs the dependents quietly we don't see what the output is... And I can't find how to force it to not be quiet.

`Collecting fairseq@ git+https://github.com/liyaodev/fairseq.git (from -r requirements.txt (line 7))
  Cloning https://github.com/liyaodev/fairseq.git to d:\aisuite\ai-bots\text-generation-webui\installer_files\pip-install-ag8hnqwq\fairseq_3a5e3d03f08644649389a1efbb640ad4
  Running command git clone --filter=blob:none --quiet https://github.com/liyaodev/fairseq.git 'D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\pip-install-ag8hnqwq\fairseq_3a5e3d03f08644649389a1efbb640ad4'
  Resolved https://github.com/liyaodev/fairseq.git to commit b963eac7a04c539ad59fb1e23277f2ff7ee29e74
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\pip-build-env-cc4njcp3\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\pip-build-env-cc4njcp3\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\pip-build-env-cc4njcp3\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\pip-build-env-cc4njcp3\overlay\Lib\site-packages\torch\__init__.py", line 141, in <module>
          raise err
      OSError: [WinError 126] The specified module could not be found. Error loading "D:\AISuite\AI-Bots\Text-Generation-Webui\installer_files\pip-build-env-cc4njcp3\overlay\Lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`
