### ISSUE TITLE
Can't run it, failed to load extension

### ISSUE THREAD

**Issue by Ryhverse** [BuffMcBigHuge/text-generation-webui-edge-tts#2]
Hello, So I'm trying to use your extension, I had a bit of a hard time to install it, git clone was giving me this in my CMD prompt: 

Cloning into 'edge_tts'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 49 (delta 11), reused 46 (delta 8), pack-reused 0
Receiving objects: 100% (49/49), 68.89 KiB | 1.91 MiB/s, done.
Resolving deltas: 100% (11/11), done.
error: invalid path 'lib/infer_pack/attentions.py:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

then I tried to download it as a zip, extracted and then copied the file onto my folder and got issues while copying with this type of files : "attentions.py:Zone.Identifier"  that got replaced by "attentions.py_Zone.Identifier" I believe the ":" caused the issue.

I was then able to install the extension manually, installing the requirements, but when I tried to load the extension, while I start the webUI, it gives me this error in my cmd prompt : 

"2023-09-27 19:40:40 INFO:Loading the extension "edge_tts"...
2023-09-27 19:40:40 ERROR:Failed to load the extension "edge_tts".
Traceback (most recent call last):
  File "D:\AI\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\AI\text-generation-webui\extensions\edge_tts\script.py", line 17, in <module>
    from modules import chat, shared, ui_chat, tts_preprocessor
ImportError: cannot import name 'tts_preprocessor' from 'modules' (unknown location)"

Do you have any ideas about what's causing the issue? Thank you for the extension, by the way, been looking for this for a really long time now!

**Comment by BuffMcBigHuge** [comment]
I made a few fixes to the extension. You will have to update `text-generation-webui`.

```
conda activate textgen
cd text-generation-webui
git pull
pip install -r requirements.txt
cd extensions/edge_tts
git pull
pip install -r requirements.txt
cd ../../
python server.py --extensions edge_tts
```

**Comment by Ryhverse** [comment]
Hey thanks for the reply, so I tried everything you said, but I couldn't load it, when opening oogabooga, it gave me this error 👍 

2023-09-28 21:39:23 INFO:Loading the extension "edge_tts"...
2023-09-28 21:39:25 ERROR:Failed to load the extension "edge_tts".
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\text-generation-webui\extensions\edge_tts\script.py", line 19, in <module>
    from modules import chat, shared, ui_chat, tts_preprocessor
ImportError: cannot import name 'tts_preprocessor' from 'modules' (unknown location)


so I edited your script.py for the tts_preprocessor to : 

**from extensions.silero_tts import tts_preprocessor**
from modules import chat, shared, ui_chat
from modules.utils import gradio

then it worked and I was able to load the extension, I also tried the testing area and my pth model worked there, but once I start chatting with the ai, I get the text reply then it says "recording a message" and doesn't do anything and in my console log I get this error (related to the changed code of line tts_preprocessor I believe) : 


Output generated in 2.74 seconds (14.21 tokens/s, 39 tokens, context 378, seed 487330545)
Traceback (most recent call last):
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "D:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\text-generation-webui\modules\chat.py", line 329, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "D:\text-generation-webui\modules\chat.py", line 297, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "D:\text-generation-webui\modules\chat.py", line 265, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
  File "D:\text-generation-webui\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "D:\text-generation-webui\modules\extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "D:\text-generation-webui\extensions\edge_tts\script.py", line 142, in output_modifier
    string = tts_preprocessor.replace_invalid_chars(html.unescape(string))
AttributeError: module 'extensions.silero_tts.tts_preprocessor' has no attribute 'replace_invalid_chars'


So I'm not sure what to do here, by the way, the previous error (that didn't let me open oogabooga): 

  File "D:\text-generation-webui\extensions\edge_tts\script.py", line 19, in <module>
    from modules import chat, shared, ui_chat, tts_preprocessor
ImportError: cannot import name 'tts_preprocessor' from 'modules' (unknown location)

was already there before sending an issue ticket yesterday, so it could be this part causing the issues ?

**Comment by BuffMcBigHuge** [comment]
I had the preprocessor added to the 'modules' folder which I added manually - so I moved it to the extension dir and referenced it there. You should be able to pull and run it correctly now. 

Thanks!

**Comment by Ryhverse** [comment]
Alright, it worked ! Thanks a lot for the great help! Closing the issue now.
