### ISSUE TITLE
 ERROR:Failed to load the extension "edge_tts".

### ISSUE THREAD

**Issue by swumagic** [BuffMcBigHuge/text-generation-webui-edge-tts#6]
2023-11-19 22:06:45 ERROR:Failed to load the extension "edge_tts".
Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\airj\text-generation-webui\text-generation-webui\extensions\edge_tts\script.py", line 24, in <module>
    from fairseq import checkpoint_utils
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\fairseq\distributed\__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\fairseq\dataclass\configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

**Comment by swumagic** [comment]
现在删除installer_files：
text-generation-webui\installer_files

然后编辑start_windows.bat，用记事本打开按ctrl+f找到python=3.11并更改为python=3.10.13然后保存。

双击start_windows.bat并让它再次下载所有文件。现在应该可以了。

问题是Python 3.11。我可以确认这会修复它。

cmd_windows.bat以管理员权限运行
输入cd extensions输入
输入输入cd edge_tts输入
输入pip install -r requirements.txt
