### ISSUE TITLE
RVC loading issue

### ISSUE THREAD

**Issue by Xeven22** [BuffMcBigHuge/text-generation-webui-edge-tts#7]
Tried multiple RVC models. But to no avail.

```
Outputting audio to extensions\edge_tts\outputs\1701066313.mp3
Running RVC
Model loaded
Audio duration: 3.096s
Traceback (most recent call last):
  File "J:\text-generation-webui-main\text-generation-webui-main\extensions\edge_tts\script.py", line 364, in tts
    audio_opt = vc.pipeline(
  File "J:\text-generation-webui-main\text-generation-webui-main\extensions/edge_tts\vc_infer_pipeline.py", line 398, in pipeline
    self.vc(
  File "J:\text-generation-webui-main\text-generation-webui-main\extensions/edge_tts\vc_infer_pipeline.py", line 251, in vc
    (net_g.infer(feats, p_len, pitch, pitchf, sid)[0][0, 0])
  File "J:\text-generation-webui-main\text-generation-webui-main\extensions/edge_tts\lib\infer_pack\models.py", line 789, in infer
    m_p, logs_p, x_mask = self.enc_p(phone, pitch, phone_lengths)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\extensions/edge_tts\lib\infer_pack\models.py", line 60, in forward
    x = self.emb_phone(phone) + self.emb_pitch(pitch)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != struct c10::Half

Traceback (most recent call last):
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "J:\text-generation-webui-main\text-generation-webui-main\installer_files\env\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\modules\chat.py", line 342, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "J:\text-generation-webui-main\text-generation-webui-main\modules\chat.py", line 310, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "J:\text-generation-webui-main\text-generation-webui-main\modules\chat.py", line 278, in chatbot_wrapper
    output['visible'][-1][1] = apply_extensions('output', output['visible'][-1][1], state, is_chat=True)
  File "J:\text-generation-webui-main\text-generation-webui-main\modules\extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\modules\extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "J:\text-generation-webui-main\text-generation-webui-main\extensions\edge_tts\script.py", line 168, in output_modifier
    wavfile.write(output_file, 44100, audio.astype(np.int16))
AttributeError: 'tuple' object has no attribute 'astype'
```

**Comment by jtabox** [comment]
Yepp, same issue here. And I know of at least one more person who has the exact same issue. Python 3.11 and CUDA 12.1 in case it matters. Great extension but unfortunately at the moment I can only run the Edge TTS part, not the RSV one.

```
Loaded 301 voices.
Found 12 rvc models.
Traceback (most recent call last):
  File "G:\ai-txt\text-generation-webui\extensions\edge_tts\script.py", line 350, in tts
    tgt_sr, net_g, vc, version, index_file, if_f0 = model_data(model_name)
                                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai-txt\text-generation-webui\extensions\edge_tts\script.py", line 305, in model_data
    tgt_sr = cpt["config"][-1]
             ~~~^^^^^^^^^^
KeyError: 'config'

Traceback (most recent call last):
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ioann\mambaforge\envs\textgen\Lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "G:\ai-txt\text-generation-webui\extensions\edge_tts\script.py", line 202, in voice_preview
    wavfile.write(output_file, 44100, audio.astype(np.int16))
                                      ^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'astype'
```

**Comment by jtabox** [comment]
After looking into it for a bit, apparently there's some models that don't have the same structure as the one this script is expecting.
The chain of errors starts from here:
```
  File "G:\ai-txt\text-generation-webui\extensions\edge_tts\script.py", line 305, in model_data
    tgt_sr = cpt["config"][-1]
             ~~~^^^^^^^^^^
KeyError: 'config'
```
The script expects the model to have a `config` key, and apparently not all models do?
For example, this one won't load (I downloaded it from https://github.com/litagin02/rvc-tts-webui):
```
>>> pth_path = 'extensions/edge_tts/rvc_models/G32k.pth'
>>> cpt = torch.load(pth_path, map_location="cpu")
>>> cpt.keys()
dict_keys(['model', 'iteration', 'learning_rate'])
```
While this one seems to work (I downloaded it from the AI Hub discord server:
```
>>> pth_path = 'extensions/edge_tts/rvc_models/sethmacfarlane.pth'
>>> cpt = torch.load(pth_path, map_location="cpu")
>>> cpt.keys()
odict_keys(['weight', 'config', 'info', 'sr', 'f0', 'version'])
```
That's about where my knowledge about ML models ends, so I assume the solution to this issue is to just not use the first type of models 😅

**Comment by BuffMcBigHuge** [comment]
Any issues with RVC should be posted [here](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI), as their code was adapted.
